apiVersion: v1
kind: Service
metadata:
  name: "ol-permission-tree-service"
spec:
  ports:
    - port: 3028
      nodePort: 32323
      protocol: TCP
  type: NodePort
  selector:
    app: "ol-permission-tree"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ol-permission-tree-deployment
  labels:
    app: ol-permission-tree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ol-permission-tree
  template:
    metadata:
      labels:
        app: ol-permission-tree
    spec:
      containers:
      - name: ol-permission-tree
        env:
        - name: PORT
          value: "3028"
        - name: NODE_HOSTNAME
          value: $NODE_HOSTNAME$
        - name: MONGO_INITDB_ROOT_USERNAME
          value: $MONGO_INITDB_ROOT_USERNAME$
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: $MONGO_INITDB_ROOT_PASSWORD$
        image: $CONTAINER_IMAGE$
        ports:
        - containerPort: 3028
        imagePullPolicy: "Always"
