version: '3'
services:
  0l:
    build: .
    environment:
      - PORT=3028
      - NODE_ENV=development
      - NODE_HOSTNAME=52.13.87.48
      - MONGO_HOST=mongodb:27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - DISABLE_SCRAPE=true
    ports:
      - "3028:3028"
    volumes:
      - ./lib:/code/lib
      - ./routers:/code/routers
      - ./index.ts:/code/index.ts
      - ./tsconfig.json:/code/tsconfig.json
      - ./package.json:/code/package.json
      - ./startCmd:/code/startCmd
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
