#!/bin/sh

if [[ "$NODE_ENV" = "development" ]]; then
 yarn dev &
else
 yarn start &
fi

if [[ "$DISABLE_SCRAPE" != "true" ]]; then
  echo "Starting scrape loop"
  ./scrapeLoop &
else
  echo "Not running scrape loop because DISABLE_SCRAPE is true"
fi

# Wait for any process to exit
wait -n
  
# Exit with status of process that exited first
exit $?
